# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: Build Web Site

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Create virtualenv and install requirements
        shell: bash
        run: |
          set -e
          if [ "${{ runner.os }}" = "Windows" ]; then
            python -m venv neuralGAM-venv
            ./neuralGAM-venv/Scripts/python.exe -m pip install --upgrade pip
            ./neuralGAM-venv/Scripts/python.exe -m pip install -r python-req.txt
            echo "RETICULATE_PYTHON=$PWD/neuralGAM-venv/Scripts/python.exe" >> $GITHUB_ENV
          else
            python -m venv neuralGAM-venv
            ./neuralGAM-venv/bin/python -m pip install --upgrade pip
            ./neuralGAM-venv/bin/python -m pip install -r python-req.txt
            echo "RETICULATE_PYTHON=$PWD/neuralGAM-venv/bin/python" >> $GITHUB_ENV
          fi

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = TRUE, run_dont_run = TRUE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: false
          branch: gh-pages
          folder: docs
